# wrangler.toml
name = "map-a-dungeon"
compatibility_date = "2023-03-01"
compatibility_flags = []

# Build configuration
[build]
command = "npm run build"

# Static site configuration
[site]
bucket = "./dist"

# Environment variables
[vars]
ENV = "production"